### ISSUE TITLE
rank=<int> doesn't seem to be working as expected, the test suites are not executing according to rank number.

### ISSUE THREAD

**Issue by anarang** [lemoncheesecake/lemoncheesecake#18]
Hi,
I noticed that the rank numbers aren't working for me, the tests execute randomly and are not following the rank number as in the suite description.
```
@lcc.suite(description="Suite: Verify search functionality", rank=2)
class test_search:
```
I also tried with rank="1" and that throws an exception which I think is valid:
```
File "/home/<username>/.virtualenvs/api-test-env/lib/python3.8/site-packages/lemoncheesecake/suite/loader.py", line 325, in load_suites_from_directory
    return sorted(sorted(filter(lambda s: not s.is_empty(), suites.values()), key=lambda s: s.name), key=lambda s: s.rank)
TypeError: '<' not supported between instances of 'str' and 'int'
```
however in one of the other projects I have been using like this:
```
@lcc.suite("Suite: Create a new product and versions", rank="2")
```
and that works.

$ lcc --version
lemoncheesecake version 1.5.2 (using Python 3.8.5 - /home/anarang/.virtualenvs/api-test-env/bin/python)

@ndelon Can you share what I might be missing here?

**Comment by ndelon** [comment]
Hello,

**About the exception**: it's normal, the rank should be an int or a float (more generally speaking: something that can be compared). Using a str instead of an int does not make sense here, and a comparison between a str and an int raises the exception that you saw.

**About the ordering issue itself**:

- does a `lcc show` shows the suites & tests in the expected order ?
- do you use the `--threads` argument of `lcc run` (in other words: are the tests parallelized) ?
- can you provide a test case that reproduce the issue ?

Regards.

**Comment by anarang** [comment]
@ndelon thank you for your response, I found the root cause, the name of the file and the name of the class weren't matching and hence the rank was messed up and the tests weren't executing according to the rank.
- `lcc show` wasn't showing the tests ordered either.
- I am not using `lcc --threads`
thanks and we can close this issue. :)

**Comment by ndelon** [comment]
Ok, great then.
