### ISSUE TITLE
Unable to pass any parameters to teardown_suite

### ISSUE THREAD

**Issue by Envy5** [lemoncheesecake/lemoncheesecake#20]
Hi Everyone,
I have noticed that teardown_suite hooks method  doesn't take any parameters whereas the setup_suite method does allow it for example a selenium webdriver instance.

if we try to pass the parameter we are presented with below error : TypeError: teardown_suite() missing 1 required positional argument: 'driver'  

fixture.py --> 

```
import os
import logging
from selenium import webdriver
import lemoncheesecake.api as lcc
from webdriver_manager.chrome import ChromeDriverManager

@lcc.fixture(names=("driver", "driver_obj"), scope="session")
def setup():
    driver = webdriver.Chrome(ChromeDriverManager(path=os.environ['PYTHONPATH']).install())
    logging.info("Webdriver has been initialised successfully")
    driver.maximize_window()
    yield driver
    lcc.log_info("Closing the browser window...")
    driver.close()
    driver.quit()
```

Testsuite.py -->

```
import lemoncheesecake.api as lcc
from webdriver_manager import driver
def setup_suite(driver):
    driver.get('https://www.google.com')

@lcc.test("Verify test")
def test_user_suite(driver):
    lcc.log_info('user name test')

def teardown_suite(driver):
    lcc.log_info(driver)
   user_logout(driver)
```

For instance the above snippet requires the driver for a user defined function inside the teardown method

**Comment by ndelon** [comment]
Hello,

First, the `teardown_suite` function does not take any fixture arguments, this is the expected behavior. Secondly, by the time  `teardown_suite` is executed the suite-scoped fixtures have already been teardown.

I think you should make your tests more independent from each other, meaning having a test-scoped new driver instance for each test and/or managing your "user" log-in/log-out on each test.

If you want to go-on on your current design, then you better initialize manually your driver instance in your `setup_suite` function, for instance (you should also use a suite-as-a-class in this case):
```python
@lcc.suite()
class Testsuite:
    def setup_suite(self):
        self.driver = [...]  # initialization code

    def test_1(self):
        # do something with self.driver

    def test_2(self):
        # do something else with self.driver

    def teardown_suite(self):
        user_logout(self.driver)
        self.driver.close()
        self.driver.quit()
```

PS: I guess that you're also the author on the same question on google groups (see https://groups.google.com/g/lemoncheesecake/c/06oaZXRyCjs/m/9qTVe0JPAgAJ) ?

Regards,

Nicolas.

**Comment by Envy5** [comment]
Thank you @ndelon 
yeah thought it might get missed in the group chat among different topics.

The reason i was looking to implement this way was to avoid redundant function calls , initialization & reduce test execution time as I wanted to scale up to multiple test suites , but seems i cannot avoid it at this stage.

**Comment by ndelon** [comment]
With the newly 1.9.0 version released, you might be interested by:
- http://docs.lemoncheesecake.io/en/latest/fixtures.html#per-thread-fixtures
- and http://docs.lemoncheesecake.io/en/latest/parallelism.html#threaded-factory

Regards,

Nicolas.
