### ISSUE TITLE
[Feature request] Ability to tag one or more bugs for each of the tests in the HTML test report.

### ISSUE THREAD

**Issue by akshayamaldhure** [lemoncheesecake/lemoncheesecake#4]
It would be great if there could be an option to tag links for one or more bugs in the test report so that the person checking out the report learns about the bugs associated with each and every test failure in a particular suite.

**Comment by ndelon** [comment]
It looks like the `link` metadata that can be associated to tests and suites and which is described here: http://docs.lemoncheesecake.io/en/latest/tests-and-suites.html#adding-metadata-to-tests-and-suites

Isn't it ?

**Comment by akshayamaldhure** [comment]
Not that one. I'm looking for an option in the report web UI wherein I can tag additional information (e.g. JIRA bug link for a given failed test) so that the developers I'm working with can easily understand the mapping of failure of my test with an existing issue.

**Comment by ndelon** [comment]
Ok, then you mean in the HTML report itself ? AFAIK, this is not technically feasible to update local file system files from the browser (or at least not without special user intervention).

What you could do is what I propose in my previous message, but you must re-run the tests when you want to associate with a new `link` (corresponding to a new bug).

Another thing I'm thinking about is command that would update the report metadata depending on metadata defined in the project's suite. Here is a usage example:
- you run the tests, and one test is failing because of a bug in the target software
- you create a ticket for this bug in your bugtracker, you get a ticket reference (example: ISSUE-1234)
- you update your test to add a new metadata (`@lcc.link(""http://bugtracker.example.com/issues/1234", "ISSUE-1234")`)
- you run a command named (for instance) `lcc report-update` that update the report depending on the metadata defined in your code
- on the next test run, the generated report will have the newly defined metadata 

What do you think of this ?

**Comment by akshayamaldhure** [comment]
Yes, in the HTML report itself directly with special user intervention. This requirement has got nothing to do with adding extra code.

Here's a typical workflow:

1. All tests are run on a Jenkins server. I've wrapped the `lcc run suite_name` command in a shell script which takes care of storing the report for each test suite run separately and the same is accessible to my teammates at a HTTP URL.
2. When a particular test in a particular suite is failed, I mark the bug with a JIRA bug link so that my teammates can see the failure cause for that test.

So I believe this has got nothing do with the lemoncheesecake's core framework, but with the report HTML itself.

Regarding what you proposed, the first approach does not sound good since that needs a re-run of tests. The second approach would need me to update the code, which I believe, again is not desirable for the use case.

Please let me know what you think of the workflow I've proposed above.

**Comment by ndelon** [comment]
I understand what you are looking for, but it cannot work with static HTML/JS, as I told previously.

Maybe you are looking for something like ReportPortal (http://reportportal.io) ?

lemoncheesecake can generate test reports into ReportPortal (see http://docs.lemoncheesecake.io/en/latest/configure-reporting-backends.html#reportportal)

**Comment by akshayamaldhure** [comment]
Ah, okay. However, setting up ReportPortal seems somewhat complicated to me in the first look. And I love the default HTML reporting provided by lemoncheesecake. :)

I believe you could tweak the code which generates the HTML report to statically add a column called "Bug link" for every "failed" test that would essentially provide a simple text box and allow anyone to edit the same and store the value somewhere locally, i.e. where the report.html is generated.

**Comment by ndelon** [comment]
Thanks for loving the HTML report (despite it would need a lot of enhancements) :-)

Using docker, you can setup ReportPortal in a few minutes (it will take more time to have something reliable with backup, etc...).

As nothing can be done here, I'm closing the ticket.
